version: 2
jobs:
  build:
    machine: true
    steps:
     - checkout
     - run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku container:login
        docker build -t revcrm:latest .
        docker tag revcrm:latest registry.heroku.com/$HEROKU_APP_NAME/web
        docker push registry.heroku.com/$HEROKU_APP_NAME/web
        heroku container:release web --app $HEROKU_APP_NAME