version: 2
jobs:
  build:
    machine: true
    steps:
     - checkout
     - run: |
        docker login --email=$HEROKU_LOGIN --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
        docker build --rm=false -t registry.heroku.com/APP_NAME/web .
        docker push registry.heroku.com/APP_NAME/web:latest