version: 2
jobs:
  build:
    machine: true
    steps:
     - checkout
     - run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku container:login
        heroku container:push web --app $HEROKU_APP_NAME
        heroku container:release web --app $HEROKU_APP_NAME