version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/openjdk:11-jdk-browsers
      - image: circleci/mongo:3.6
    steps:
      - checkout
      - restore_cache:
          key: revcrm-deps-v1-{{ checksum "build.gradle" }}
      
      - run:
          name: Build & Test
          command: gradle build --stacktrace

      - run:
          name: Collect test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/junitXml/.*xml" -exec cp {} ~/junit/ \;

      - store_test_results:
          path: ~/junit

      - save_cache:
          paths:
            - ~/.gradle
          key: revcrm-deps-v1-{{ checksum "build.gradle" }}
      
      - store_artifacts:
          path: revcrm-server/build/distributions/revcrm-server-1.0.tar
